# Generated by Django 3.0.5 on 2022-12-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
