# Generated by Django 3.0.5 on 2022-12-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_auto_20221211_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='pizzas/media/images/'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_image',
            field=models.ImageField(blank=True, null=True, upload_to='imgages'),
        ),
    ]
