# Generated by Django 3.0.5 on 2022-12-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_auto_20221211_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_image',
            field=models.ImageField(blank=True, null=True, upload_to='imgages/'),
        ),
    ]
